### ISSUE TITLE
`docker compose up` doesn't work with M1

### ISSUE THREAD

**Issue by prajjwol** [Pocket/collection-api#336]
It's a known issue that some docker containers don't work with the M1 chip. https://github.com/docker-library/mysql/issues/778

The version that the project is using specifically doesn't work with m1 throwing
```
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:7cf2e7d7ff876f93c8601406a5aa17484e6623875e
64e7acc71432ad8e0a3d7e: not found
```

However, using the latest image seems to work. Maybe we can pin the latest version (8.x) instead of 5.7 here? 

```
-    image: mysql:5.7
+    image: mysql:latest
```

**Comment by nina-py** [comment]
Hi @prajjwol, thanks for bringing this up! We use MySQL 5.7 on production so we pin the image to match.
